[server]
headless = true
address = "0.0.0.0"
port = 8000
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#177ddc"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#111827"
textColor = "#e5e7eb"
font = "sans serif"
